### ISSUE TITLE
Polymer telemetry type not generated

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/gen-typescript-declarations#63]
The telemetry namespace is generated empty:

```ts
namespace telemetry {
}
```

But its definition lists several properties: https://github.com/Polymer/polymer/blob/d7ea2464cd7e798c1bc4ebf25e12d17c43a6f8b4/lib/mixins/element-mixin.html#L671-L716

**Comment by 43081j** [comment]
You can get the methods to be produced by adding `@memberof Polymer.telemetry` to them.

The function scanner picks these up i imagine, but requires a `@memberof` tag even if it is inside an object literal with a `@namespace` (this is because we don't scan them in the same context/scope, iirc).

The properties are a little different. I'm not sure if we pick those up yet in the analyser

**Comment by TimvdLippe** [comment]
This has now been fixed: https://unpkg.com/@polymer/polymer@3.0.5/lib/mixins/element-mixin.d.ts
