### ISSUE TITLE
Do behaviors require stand-in properties?

### ISSUE THREAD

**Issue by kito99** [Polymer/gen-typescript-declarations#68]
So, unless I'm mistaken, since behaviors are declared as interfaces, we need to add stand-in declarations just as we did with PolymerTS:

```typescript
class MyappView1 extends Polymer.mixinBehaviors([Polymer['AppLocalizeBehavior']], Polymer.Element) implements AppLocalizeBehavior {

// actual code

		// Stand-in declarations from AppLocalizeBehavior
		language: string|null|undefined;
		resources: object|null|undefined;
		formats: object|null|undefined;
		useKeyIfMissing: boolean|null|undefined;
		readonly localize: Function|null|undefined;
		bubbleEvent: boolean|null|undefined;
		loadResources: (path: string, language?: string, merge?: boolean) =>  any;

}
```

Is this the correct way to use a behavior?

**Comment by aomarks** [comment]
I would cast the result of `mixinBehaviors` to a constructor that includes the generated interface. That way you don't need to redeclare anything. Getting `mixinBehaviors` to do this automatically seems potentially impossible.

```ts
const myElementBase =
    Polymer.mixinBehaviors([ Polymer.AppLocalizeBehavior ], Polymer.Element) as
    new () => Polymer.Element & Polymer.AppLocalizeBehavior;

class MyElement extends myElementBase {
   ...
}
```

I just filed #70 to address the fact that we don't declare the actual object representing the behavior (which is why you had to do `Polymer['AppLocalizeBehavior']`). In the short term you could do this, and then just remove it once the declarations include it:

```ts
declare namespace Polymer { const AppLocalizeBehavior: object; }
```

**Comment by kito99** [comment]
Thanks! I'll give this a shot and close it once I get things working.

**Comment by kito99** [comment]
That worked. Thanks!
