### ISSUE TITLE
Delete type declaration files without any content

### ISSUE THREAD

**Issue by stramel** [Polymer/gen-typescript-declarations#96]
You can see more what I mean here: https://github.com/PolymerElements/marked-element/pull/88/files#diff-8c66e52d6509ca0676ce2b5fbc5e4c4e

```ts
/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   marked-import.html
 */
```

I have removed the reference that was there in the `gen-tsd.json`.

```json
{
  "removeReferences": [
    "../marked/lib/marked.d.ts"
  ]
}
```

**Comment by aomarks** [comment]
We actually prefer to keep these. The reason is that this tool generally mirrors the HTML import graph in it the `/// <reference ...` statements it inserts. It's simpler to just let files with no declarations exist as empty files, than for all of the other repos that **depend** on this one to know to remove that reference.
